## Análise Exploratória de Dados - Vendas de Tacos em 2024 e 2025

Nesse notebook, estou realizando a Análise Exploratória de Dados e respondendo perguntas criadas pelo ChatGPT a partir do dataset 
Taco Sales Dataset (2024-2025), disponível no Kaggle. <br>
Link do dataset: https://www.kaggle.com/datasets/atharvasoundankar/taco-sales-dataset-20242025

Etapa 1: Importando e lendo os dados

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
# carregando o dataset
df = pd.read_csv('taco_sales_(2024-2025).csv')

In [12]:
# número de linhas e colunas
df.shape

(1000, 13)

In [13]:
# visualizando as 5 primeiras linhas do df
df.head(5)

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Taco Size,Taco Type,Toppings Count,Distance (km),Price ($),Tip ($),Weekend Order
0,770487,El Taco Loco,New York,01-08-2024 14:55,01-08-2024 15:36,41,Regular,Chicken Taco,5,3.01,9.25,2.22,False
1,671858,El Taco Loco,San Antonio,23-11-2024 17:11,23-11-2024 17:25,14,Regular,Beef Taco,1,6.20,4.25,3.01,True
2,688508,Taco Haven,Austin,21-11-2024 20:24,21-11-2024 21:02,38,Large,Pork Taco,2,20.33,7.00,0.02,False
3,944962,Spicy Taco House,Dallas,21-09-2024 06:43,21-09-2024 07:28,45,Regular,Chicken Taco,2,3.00,5.50,1.90,True
4,476417,Casa del Taco,San Antonio,24-07-2024 11:01,24-07-2024 11:16,15,Large,Pork Taco,0,24.34,4.50,1.14,False

In [14]:
# também é possível ver as últimas linhas do df
df.tail()

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Taco Size,Taco Type,Toppings Count,Distance (km),Price ($),Tip ($),Weekend Order
995,164891,La Vida Taco,Austin,27-05-2024 11:12,27-05-2024 12:11,59,Large,Veggie Taco,2,20.04,7.00,2.80,False
996,232442,The Taco Stand,San Antonio,03-04-2025 20:51,03-04-2025 21:29,38,Regular,Fish Taco,0,13.69,3.00,1.38,False
997,251729,Urban Tacos,Houston,23-01-2025 05:33,23-01-2025 06:41,68,Regular,Pork Taco,2,4.07,5.50,2.00,False
998,940215,Taco Fiesta,San Antonio,05-09-2024 15:49,05-09-2024 16:38,49,Regular,Veggie Taco,5,14.56,9.25,1.89,False
999,326183,Grande Tacos,Phoenix,19-10-2024 14:21,19-10-2024 14:38,17,Large,Chicken Taco,5,5.66,10.75,3.66,True

In [15]:
# listando as colunas
df.columns

Index(['Order ID', 'Restaurant Name', 'Location', 'Order Time',
       'Delivery Time', 'Delivery Duration (min)', 'Taco Size', 'Taco Type',
       'Toppings Count', 'Distance (km)', 'Price ($)', 'Tip ($)',
       'Weekend Order'],
      dtype='object')

In [16]:
# verificando de que tipo são nossos dados
df.dtypes

Order ID                     int64
Restaurant Name             object
Location                    object
Order Time                  object
Delivery Time               object
Delivery Duration (min)      int64
Taco Size                   object
Taco Type                   object
Toppings Count               int64
Distance (km)              float64
Price ($)                  float64
Tip ($)                    float64
Weekend Order                 bool
dtype: object

In [17]:
# verificando algumas informações numéricas do df
df.describe()

,Order ID,Delivery Duration (min),Toppings Count,Distance (km),Price ($),Tip ($)
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000
mean,552504.865000,50.93000,2.529000,13.073420,6.908250,1.806110
std,255948.779709,23.22754,1.717005,7.142268,2.310137,1.132035
min,101139.000000,10.00000,0.000000,0.510000,3.000000,0.010000
25%,331796.750000,30.00000,1.000000,6.972500,4.500000,0.907500
50%,559740.000000,53.00000,3.000000,13.200000,6.750000,1.760000
75%,771781.750000,71.00000,4.000000,19.242500,9.250000,2.520000
max,999138.000000,90.00000,5.000000,24.980000,10.750000,4.980000

## Etapa 2: Preparação dos dados

• Eliminando linhas e colunas irrelevantes<br>
• Identificando colunas duplicadas<br>
• Renomeando colunas<br>
• Criando features<br>

In [18]:
# exibindo novamente o df para analisar que dados precisamos manter
df.head()

,Order ID,Restaurant Name,Location,Order Time,Delivery Time,Delivery Duration (min),Taco Size,Taco Type,Toppings Count,Distance (km),Price ($),Tip ($),Weekend Order
0,770487,El Taco Loco,New York,01-08-2024 14:55,01-08-2024 15:36,41,Regular,Chicken Taco,5,3.01,9.25,2.22,False
1,671858,El Taco Loco,San Antonio,23-11-2024 17:11,23-11-2024 17:25,14,Regular,Beef Taco,1,6.20,4.25,3.01,True
2,688508,Taco Haven,Austin,21-11-2024 20:24,21-11-2024 21:02,38,Large,Pork Taco,2,20.33,7.00,0.02,False
3,944962,Spicy Taco House,Dallas,21-09-2024 06:43,21-09-2024 07:28,45,Regular,Chicken Taco,2,3.00,5.50,1.90,True
4,476417,Casa del Taco,San Antonio,24-07-2024 11:01,24-07-2024 11:16,15,Large,Pork Taco,0,24.34,4.50,1.14,False

In [19]:
# usando o atributo dtypes, vemos que as colunas "Order Time" e "Delivery Time" são do tipo object.
df.dtypes

Order ID                     int64
Restaurant Name             object
Location                    object
Order Time                  object
Delivery Time               object
Delivery Duration (min)      int64
Taco Size                   object
Taco Type                   object
Toppings Count               int64
Distance (km)              float64
Price ($)                  float64
Tip ($)                    float64
Weekend Order                 bool
dtype: object

In [37]:
# Vamos transformá-las em datetime
#df[['Order Time','Delivery Time']] = df[['Order Time','Delivery Time']].apply(pd.to_datetime)

df['Order Time'] = pd.to_datetime(df['Order Time'], format='mixed')
df['Delivery Time'] = pd.to_datetime(df['Delivery Time'], format='mixed')

In [38]:
df.dtypes

Order ID                            int64
Restaurant Name                    object
Location                           object
Order Time                 datetime64[ns]
Delivery Time              datetime64[ns]
Delivery Duration (min)             int64
Taco Size                          object
Taco Type                          object
Toppings Count                      int64
Distance (km)                     float64
Price ($)                         float64
Tip ($)                           float64
Weekend Order                        bool
dtype: object

In [30]:
# vamos utilizar uma função de agregação para extrair mais informações sobre os valores nulos
df.isna().sum()

Order ID                   0
Restaurant Name            0
Location                   0
Order Time                 0
Delivery Time              0
Delivery Duration (min)    0
Taco Size                  0
Taco Type                  0
Toppings Count             0
Distance (km)              0
Price ($)                  0
Tip ($)                    0
Weekend Order              0
dtype: int64

In [29]:
# Agora, vamos verificar se temos dados duplicados, localizando-os (se houverem)
df.loc[df.duplicated()]

Empty DataFrame
Columns: [Order ID, Restaurant Name, Location, Order Time, Delivery Time, Delivery Duration (min), Taco Size, Taco Type, Toppings Count, Distance (km), Price ($), Tip ($), Weekend Order]
Index: []

## Etapa 3: Respondendo as perguntas

1. Quantos pedidos foram feitos no total?

In [57]:
# Como não temos registros duplicados, basta indicar o número de linhas
print(f"Foram feitos {len(df)} pedidos")

Foram feitos 1000 pedidos

2. Quais são os restaurantes únicos que aparecem no dataset?

In [28]:
# removi duplicatas e ordenei por ordem alfabética
df['Restaurant Name'].drop_duplicates().sort_values().reset_index(drop=True)

0        Casa del Taco
1         El Taco Loco
2         Grande Tacos
3         La Vida Taco
4     Spicy Taco House
5          Taco Fiesta
6           Taco Haven
7    Taco Time Express
8       The Taco Stand
9          Urban Tacos
Name: Restaurant Name, dtype: object

3. Quantos pedidos foram feitos em cada ano (2024 vs 2025)?

In [49]:
# usando o value_counts e agrupando por ano
df['Order Time'].dt.year.value_counts().sort_index()

Order Time
2024    698
2025    302
Name: count, dtype: int64

In [48]:
# decidi também deixar registrado minha primeira forma de resolução da questão
dados_ano = df[df['Order Time'].dt.year==2025]

print(f'Pedidos em 2024: {len(df) - len(dados_ano)}\nPedidos em 2025: {len(dados_ano)}')

Pedidos em 2024: 698
Pedidos em 2025: 302

4. Qual foi a média de gorjeta (Tip ($)) por pedido?

In [56]:
# utilizando .mean() para calcular a média
media_gorjeta = df['Tip ($)'].mean()
print(f"A média de gorjeta por pedido foi de ${media_gorjeta:.2f}")

A média de gorjeta por pedido foi de $1.81

5. Qual o pedido com o maior valor total (Price + Tip)?

In [64]:
valor_pedido = df['Price ($)'] + df['Tip ($)']

print(f'O pedido de maior valor custou ${valor_pedido.max():.2f}')

O pedido de maior valor custou $15.47

6. Quantos pedidos foram feitos aos fins de semana? E durante a semana?

In [91]:
# aproveitei para usar a operação de negação que vi aplicação recentemente
print(f"Pedidos feitos aos fins de semana: {df['Weekend Order'].sum()} pedidos")
print(f"Pedidos feitos durante a semana: {(~df['Weekend Order']).sum()} pedidos")

Pedidos feitos aos fins de semana: 275 pedidos
Pedidos feitos durante a semana: 725 pedidos

In [92]:
# outra alternativa, criada com o ChatGPT
df['Weekend Order'].value_counts().rename(index={True: 'Fins de semana', False: 'Dias úteis'})

Weekend Order
Dias úteis        725
Fins de semana    275
Name: count, dtype: int64

In [81]:
weekend_order = df['Weekend Order']==True
print(f'Pedidos feitos aos fins de semana: {weekend_order.sum()}\
    \nPedidos feitos durante a semana: {len(df) - weekend_order.sum()}')

Pedidos feitos aos fins de semana: 275
Pedidos feitos durante a semana: 725

7. Qual restaurante teve o maior número de pedidos?

In [110]:
df['Restaurant Name'].value_counts()

Restaurant Name
Urban Tacos          117
Grande Tacos         106
The Taco Stand       105
Casa del Taco        104
Spicy Taco House     100
Taco Fiesta           99
La Vida Taco          98
Taco Haven            95
Taco Time Express     91
El Taco Loco          85
Name: count, dtype: int64

8. Qual é o tempo médio de entrega por restaurante?

In [131]:
# utilizando o groupby para agrupar os restaurantes e calculando a media da coluna de duração. O sort_values mostra quem entrega mais rapido
df.groupby('Restaurant Name')['Delivery Duration (min)'].mean().round(2).sort_values()

Restaurant Name
La Vida Taco         47.05
El Taco Loco         48.24
Taco Fiesta          49.94
Casa del Taco        50.30
Grande Tacos         51.48
Urban Tacos          51.64
Spicy Taco House     51.90
Taco Haven           51.94
Taco Time Express    52.71
The Taco Stand       53.56
Name: Delivery Duration (min), dtype: float64

9. Qual é o tamanho de taco mais vendido? E o tipo mais popular?

In [150]:
# usando a mesma lógica da 8 para mostrar o tamanho
df.groupby('Taco Size')['Order ID'].count().sort_values(ascending=False)

Taco Size
Regular    502
Large      498
Name: Order ID, dtype: int64

In [149]:
df.groupby('Taco Type')['Order ID'].count().sort_values(ascending=False)

Taco Type
Chicken Taco    218
Fish Taco       211
Veggie Taco     197
Pork Taco       192
Beef Taco       182
Name: Order ID, dtype: int64

10. Qual foi o ticket médio por tipo de taco?

Qual é o tempo médio de entrega por restaurante?

Qual é o tamanho de taco mais vendido? E o tipo mais popular?

Qual foi o ticket médio (Price) por tipo de taco?

Qual a distância média percorrida por entrega para cada localização?

Existe diferença no tempo médio de entrega entre os tamanhos de taco (Taco Size)?

📈 Perguntas temporais e de tendência:
Qual foi o mês com maior volume de pedidos?

Como variou o número de pedidos por dia da semana?

Existe diferença no valor médio das gorjetas entre os anos de 2024 e 2025?

Pedidos feitos aos fins de semana têm gorjeta maior?

Existe tendência de pedidos maiores (em valor ou toppings) ao longo do tempo?

🧠 Desafios mais analíticos:
Clientes pedem mais toppings em tacos de certo tipo ou tamanho?

Pedidos que têm maiores distâncias tendem a ter gorjetas maiores?

Existe relação entre o tempo de entrega e o valor da gorjeta? (correlação)

In [ ]:
# Aqui vemos a correlação entre os dados (valores entre -1 e 1)
df.corr()

,Order ID,Delivery Duration (min),Toppings Count,Distance (km),Price ($),Tip ($),Weekend Order
Order ID,1.000000,-0.002607,-0.035898,-0.021335,-0.053898,-0.016472,0.042922
Delivery Duration (min),-0.002607,1.000000,-0.029215,-0.055558,-0.035233,-0.017751,-0.042518
Toppings Count,-0.035898,-0.029215,1.000000,0.020239,0.945928,0.049557,0.013735
Distance (km),-0.021335,-0.055558,0.020239,1.000000,0.031482,0.007936,-0.009600
Price ($),-0.053898,-0.035233,0.945928,0.031482,1.000000,0.059377,0.001194
Tip ($),-0.016472,-0.017751,0.049557,0.007936,0.059377,1.000000,0.402381
Weekend Order,0.042922,-0.042518,0.013735,-0.009600,0.001194,0.402381,1.000000